// Landing-page screenshot capture.
//
// Boots the REAL React app via Vite, stubs the Tauri IPC layer with
// landing/shots/mock-init.js, drives Chromium through the app, and writes
// curated stills to landing/assets/ + an OG image to landing/og-image.png.
//
//   node landing/shots/capture.mjs                    # Korean UI, all 9 shots + OG
//   CAPTURE_LANG=en node landing/shots/capture.mjs    # English UI, README shots only → assets/en/
//
// The EN pass exists for README.md: an English document with Korean-UI
// screenshots reads as an unlocalized product. Fixture DATA (file names,
// subtitle lines) stays Korean/Japanese in both passes — that's the product
// being shown, not the chrome.
//
// Touches no production source. Sample media is generated by gen-sample.sh
// (ffmpeg) and served via a Playwright route, so the waveform is real.
import { createServer } from "vite";
import { chromium } from "playwright";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { readFile, mkdir } from "node:fs/promises";
import { execFile } from "node:child_process";
import { promisify } from "node:util";

const execFileP = promisify(execFile);
const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..", "..");
const assetsDir = resolve(__dirname, "..", "assets");
const landingDir = resolve(__dirname, "..");

const VIEWPORT = { width: 1600, height: 1000 }; // 16:10
const SCALE = 1.5;
const SAMPLE = resolve(__dirname, "assets", "sample.mp4");

// UI language of the captured chrome. i18n reads localStorage("ui_language")
// before config arrives, so an init script is all it takes to switch.
const LANG = process.env.CAPTURE_LANG === "en" ? "en" : "ko";
const EN_ONLY_README_SHOTS = LANG === "en"; // EN pass captures the 5 README shots
const outDir = LANG === "en" ? resolve(assetsDir, "en") : assetsDir;

// Navigation selectors are UI strings, so they follow LANG. Fixture data
// (file names, subtitle text, vocab names) is language-independent.
const T = {
  settings: LANG === "en" ? "Settings" : "설정",
  models: LANG === "en" ? "Models" : "모델",
  dashboard: LANG === "en" ? "Dashboard" : "작업 관리",
  presets: LANG === "en" ? "Presets" : "프리셋",
  jobPresetsTab: LANG === "en" ? /Job Presets/ : /작업 프리셋/,
};

const log = (...a) => console.log(`[capture:${LANG}]`, ...a);

async function main() {
  await mkdir(outDir, { recursive: true });
  const mockInit = await readFile(resolve(__dirname, "mock-init.js"), "utf8");
  const sampleBytes = await readFile(SAMPLE);

  log("starting vite…");
  const server = await createServer({
    root: projectRoot,
    server: { port: 5599, strictPort: false },
    logLevel: "warn",
  });
  await server.listen();
  const url = server.resolvedUrls.local[0];
  log("vite at", url);

  const browser = await chromium.launch();
  const context = await browser.newContext({
    viewport: VIEWPORT,
    deviceScaleFactor: SCALE,
    colorScheme: "dark",
  });

  // Serve the sample clip wherever convertFileSrc points the app.
  await context.route("**/__sample_media__.mp4", (route) =>
    route.fulfill({ status: 200, contentType: "video/mp4", body: sampleBytes }),
  );

  const page = await context.newPage();
  await page.addInitScript(`localStorage.setItem("ui_language", ${JSON.stringify(LANG)});`);
  await page.addInitScript(mockInit);
  page.on("pageerror", (e) => log("PAGEERROR:", e.message));

  await page.goto(url, { waitUntil: "networkidle" });

  // ── Dashboard / batch queue ──────────────────────────────────────
  await page.getByText("雨の約束_第3話.mkv").first().waitFor({ timeout: 15000 });
  await page.waitForTimeout(600);
  await shot(page, "batch.png");

  // ── Settings → Models ────────────────────────────────────────────
  await page.getByText(T.settings, { exact: true }).first().click();
  await page.getByText(T.models, { exact: true }).first().click();
  await page.waitForTimeout(700);
  await shot(page, "models.png");

  // ── Editor (open the first completed job) ────────────────────────
  await page.getByText(T.dashboard, { exact: true }).first().click();
  await page.waitForTimeout(300);
  await page.getByText("雨の約束_第3話.mkv").first().click();
  // Wait for the subtitle list + a real waveform to render.
  const pickLine = page.getByText("내일, 역 앞에서 기다릴게.").first();
  await pickLine.waitFor({ timeout: 15000 });
  await page.waitForTimeout(2500); // peaks decode + draw
  // Select a line so the edit panel (original + translation fields) fills.
  await pickLine.click();
  await page.waitForTimeout(500);
  await shot(page, "editor.png");

  // Speaker-focused crop: the subtitle list panel (the scroll viewport
  // that contains the dialogue lines), showing speaker labels + dual lang.
  const list = page
    .locator("[data-radix-scroll-area-viewport]")
    .filter({ hasText: "내일, 역 앞에서 기다릴게." })
    .first();
  if (await list.count()) {
    await list.screenshot({ path: resolve(outDir, "speaker.png") });
    log("wrote speaker.png (element)");
  } else {
    await shot(page, "speaker.png");
  }

  // ── Presets page (작업 프리셋 tab) ───────────────────────────────
  // Tab triggers carry a count Badge, so match by role, not exact text.
  await page.getByText(T.presets, { exact: true }).first().click();
  await page.getByRole("tab", { name: T.jobPresetsTab }).waitFor({ timeout: 10000 });
  await page.waitForTimeout(600);
  await shot(page, "presets.png");

  if (!EN_ONLY_README_SHOTS) {
    // ── Vocabulary (용어사전 tab) ───────────────────────────────────
    await page.getByRole("tab", { name: /용어사전/ }).click();
    await page.getByText("애니 고유명사").first().waitFor({ timeout: 10000 });
    // Expand the first dictionary so the source→target table shows.
    await page.getByText("애니 고유명사").first().click();
    await page.waitForTimeout(500);
    await shot(page, "vocab.png");

    // ── Settings / general (테마 & 언어) ────────────────────────────
    await page.getByText("설정", { exact: true }).first().click();
    await page.getByText("일반", { exact: true }).first().click();
    await page.getByText("UI 언어", { exact: true }).first().waitFor({ timeout: 10000 });
    await page.waitForTimeout(500);
    await shot(page, "theme.png");

    // ── New-job dialog (드래그 앤 드롭) ─────────────────────────────
    await page.getByText("작업 관리", { exact: true }).first().click();
    await page.waitForTimeout(300);
    await page.getByRole("button", { name: "새 작업" }).first().click();
    await page.getByText("파일을 드래그 앤 드롭하거나 클릭하여 찾아보기").first().waitFor({ timeout: 10000 });
    await page.waitForTimeout(500);
    await shot(page, "dragdrop.png");
  }

  await context.close();

  if (!EN_ONLY_README_SHOTS) {
    // ── Wizard pass: StepEnvironment (하드웨어 프로필) ──────────────
    const wctx = await browser.newContext({ viewport: VIEWPORT, deviceScaleFactor: SCALE, colorScheme: "dark" });
    await wctx.route("**/__sample_media__.mp4", (r) => r.fulfill({ status: 200, contentType: "video/mp4", body: sampleBytes }));
    const wpage = await wctx.newPage();
    // Boot into the wizard at the environment step (profile + detected GPU).
    await wpage.addInitScript("window.__MOCK_OVERRIDE__ = { wizard_completed: false, wizard_step: 2 };");
    await wpage.addInitScript(mockInit);
    await wpage.goto(url, { waitUntil: "networkidle" });
    await wpage.waitForTimeout(1500);
    await shot(wpage, "hardware.png");
    await wctx.close();
  }

  await browser.close();
  await server.close();

  if (!EN_ONLY_README_SHOTS) {
    // ── OG image: 1200×630 from the editor still (ffmpeg cover-crop) ──
    await execFileP("ffmpeg", [
      "-y", "-i", resolve(assetsDir, "editor.png"),
      "-vf", "scale=1200:630:force_original_aspect_ratio=increase,crop=1200:630",
      resolve(landingDir, "og-image.png"),
    ]);
    log("wrote og-image.png (1200×630)");
  }
  log("done.");
}

async function shot(page, name) {
  await page.screenshot({
    path: resolve(outDir, name),
    clip: { x: 0, y: 0, ...VIEWPORT },
  });
  log("wrote", name);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
